# .pre-commit-config.yaml — ycurl project (ruff‑centric, revised)
---
minimum_pre_commit_version: "3.3.0"

default_language_version:
  python: python3.13.2

default_stages: [pre-commit, pre-push]

repos:
  # ───────────── Ruff (formatter + linter + import sorting + Bandit rules) ─────────────
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        args:
          - --fix
          - --extend-select
          - I,S            # import sorting + security rules
      - id: ruff-format

  # ───────────── Static typing ─────────────
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          - --install-types
          - --non-interactive
          - --strict
          - --config-file=mypy.ini
          - --explicit-package-bases
        entry: mypy
        require_serial: true
        additional_dependencies:
          - types-PyYAML
          - types-click
          - types-requests

  # ───────────── Security / secrets ─────────────
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        name: bandit (deep security scan)
        args: ["-c", "pyproject.toml", "-r", "."]
        additional_dependencies: ["bandit[toml]"]
        stages: [pre-push]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  # ───────────── YAML & JSON hygiene ─────────────
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        # Relax 80‑char rule: allow 120 for config readability
        args:
          - -d
          - '{extends: default, rules: {line-length: {max: 120}}}'
        files: "\\.(ya?ml)$"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict

  # ───────────── Shell scripts ─────────────
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        files: "\\.(sh|bash)$"

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.11.0-1
    hooks:
      - id: shfmt

  # ───────────── Commit message linting ─────────────
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.7.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

ci:
  parallel: true
