# .pre-commit-config.yaml
---
minimum_pre_commit_version: "3.0.0"
default_language_version:
  python: python3.11          # keep in sync with CI & hatch env

repos:
  # ───────────────────────────── Formatting & Imports ────────────────────────────
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        # run before black so black can make final tweaks
        stages: [commit, push]
        always_run: true

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
        stages: [commit, push]
        always_run: true

  # ─────────────────────────────── Code Quality ──────────────────────────────────
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0
    hooks:
      - id: ruff
        args: ["--fix", "--show-source"]   # auto‑fix where possible
        exclude: |
          tests/data/.*                   # skip static fixtures if any
        stages: [commit, push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args:
          [
            "--install-types",
            "--non-interactive",
            "--strict",
            "src/ycurl",
          ]
        additional_dependencies:
          [
            "types-PyYAML",
            "types-requests",
            "types-click",
          ]
        stages: [commit, push]

  # ───────────────────────────── Security / Secrets ──────────────────────────────
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        name: bandit (security static analysis)
        args: ["-r", "src/ycurl", "-ll"]   # level: low+medium+high
        stages: [commit, push]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        stages: [commit, push]

  # ─────────────────────────────── YAML & JSON ───────────────────────────────────
  - repo: https://github.com/pre-commit/mirrors-yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: "\\.(ya?ml)$"
        stages: [commit, push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml          # syntax check only
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: debug-statements
      - id: check-merge-conflict

  # ─────────────────────────────── Shell Scripts ─────────────────────────────────
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        files: "\\.(sh|bash)$"

  - repo: https://github.com/mvdan/sh
    rev: v4.6.0
    hooks:
      - id: shfmt
        args: ["-i", "2", "-ci"]
        files: "\\.(sh|bash)$"

  # ───────────────────────────── Commit Message ──────────────────────────────────
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.21.1
    hooks:
      - id: commitizen
        stages: [commit-msg]     # enforces Conventional Commits

# Run hooks automatically on git push in addition to commit
# (helps catch issues in bulk operations like `git rebase -i`)
ci:
  parallel: true
